# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8866
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  setting:
    custom-code: 500
    enable-footer-custom: false
    
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: res-sharing
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

storage:
  enabled: true
  config:
    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
    type: local
    domain: http://localhost:8080
  local:
    path: D://upload

jony:
  xss:
    enabled: true
    exclude-urls:
      - /jony-generator/**
  security:
    # 2小时过期
    access-token-expire: 7200
    # 14天过期
    refresh-token-expire: 1209600

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jony.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

#easy trans 数据翻译组件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true

# selt
shuishu:
  # 登录策略（默认ONE：com.shuishu.demo.security.common.config.security.LoginPolicyConfig.getLoginPolicy）
  # ONE: 达到最大客户端登录人数，将最早登录的客户端给踢掉
  # TWO: 达到最大客户端登录人数，不允许登录
  login-policy: TWO
  token:
    secret: spring_security_examples
    auth-token: AuthToken
    # 此刷新token就是记住我功能的 token
    remember-me-token: RememberMeToken
    # auth-token 有效时间（秒） 1小时 = 1 * 60 * 60
    expire-time: 3600
    # refresh-token 有效时间（秒）： 30天 = 1 * 60 * 60 * 24 * 30
    remember-me-token-expire-time: 2592000
    # auth-token 距离过期时间 expire-time 还有多少秒，重新设置有效时间为 expire-time：5分钟 = 1 * 60 * 5
    surplus-refresh-time: 300